# Generated by Django 5.2.5 on 2025-08-08 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('electrical', 'ইলেকট্রিক্যাল কাজ'), ('solar', 'সোলার সলিউশন'), ('cctv', 'সিসিটিভি/সিকিউরিটি'), ('ac', 'এসি সার্ভিস'), ('ips', 'আইপিএস/পাওয়ার ব্যাকআপ'), ('fridge', 'রেফ্রিজারেটর/অ্যাপ্লায়েন্স'), ('plumbing', 'প্লাম্বিং/পাইপিং'), ('other', 'অন্যান্য')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(choices=[('electrical', 'ইলেকট্রিক্যাল কাজ'), ('solar', 'সোলার সলিউশন'), ('cctv', 'সিসিটিভি/সিকিউরিটি'), ('ac', 'এসি সার্ভিস'), ('ips', 'আইপিএস/পাওয়ার ব্যাকআপ'), ('fridge', 'রেফ্রিজারেটর/অ্যাপ্লায়েন্স'), ('plumbing', 'প্লাম্বিং/পাইপিং'), ('other', 'অন্যান্য')], default='other', max_length=20)),
                ('message', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
