# Generated by Django 5.2.5 on 2025-08-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contactmessage_category_supportchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supportchatmessage',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
