# Generated by Django 5.2.5 on 2025-08-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bn_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Divisions',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bn_name', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='location.division')),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bn_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazilas', to='location.district')),
            ],
            options={
                'verbose_name_plural': 'Upazilas',
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bn_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upazila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions', to='location.upazila')),
            ],
            options={
                'verbose_name_plural': 'Unions',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bn_name', models.CharField(blank=True, max_length=100, null=True)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='location.union')),
            ],
            options={
                'verbose_name_plural': 'Villages',
            },
        ),
    ]
